CREATE DATABASE ZENAS_ATHLEISURE_DB;
CREATE SCHEMA PRODUCTS;

DROP SCHEMA ZENAS_ATHLEISURE_DB.PUBLIC;

CREATE STAGE ZENAS_ATHLEISURE_DB.PRODUCTS.UNI_KLAUS_CLOTHING 
	URL = 's3://uni-klaus/clothing' 
	DIRECTORY = ( ENABLE = true );

LIST @ZENAS_ATHLEISURE_DB.PRODUCTS.UNI_KLAUS_CLOTHING 

CREATE STAGE ZENAS_ATHLEISURE_DB.PRODUCTS.UNI_KLAUS_ZMD 
	URL = 's3://uni-klaus/zenas_metadata' 
	DIRECTORY = ( ENABLE = true );

LIST @ZENAS_ATHLEISURE_DB.PRODUCTS.UNI_KLAUS_ZMD;

CREATE OR REPLACE STAGE ZENAS_ATHLEISURE_DB.PRODUCTS.UNI_KLAUS_SNEAKERS 
	URL = 's3://uni-klaus/sneakers' 
	DIRECTORY = ( ENABLE = true );

LIST @ZENAS_ATHLEISURE_DB.PRODUCTS.UNI_KLAUS_SNEAKERS
